name: "Feature Request"
description: "Suggest an enhancement or new capability"
title: "[FEATURE] Short summary"
labels:
  - feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Describe the pain point or workflow gap you are facing.
      placeholder: "Teams cannot share locator knowledge across projects"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Outline your ideal workflow, UX, or configuration.
      placeholder: "Add a shared locator library with role-based approvals"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How will we know this request is complete?
  - type: input
    id: docs
    attributes:
      label: Requires documentation update?
      placeholder: "Yes/No"
  - type: input
    id: dependencies
    attributes:
      label: Related issues/PRs
      description: Link any existing discussions or workstreams
